FROM debian

MAINTAINER dtelega <dtelega@student.unit.ua>

RUN	apt-get update && \
	apt-get upgrade && \
	apt-get install -y git build-essential && \
	apt-get install -y emacs && \
	apt-get install make -y

CMD /bin/bash
